version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "alembic upgrade head"
    depends_on:
      postgres:
        condition: service_healthy

  scanledger:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./unit/bundle.pem:/docker-entrypoint.d/bundle.pem:ro
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully

volumes:
  pgdata:
