"""Changed "token_expire" to "token_expire_at"

Revision ID: 9a5c26643f8a
Revises: 66d3144b80f7
Create Date: 2025-07-03 13:50:14.481812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a5c26643f8a'
down_revision: Union[str, None] = '66d3144b80f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expires_at', sa.Integer(), nullable=True))
    op.drop_column('users', 'token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expires', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'token_expires_at')
    # ### end Alembic commands ###
